// <auto-generated />
using System;
using LandPApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LandPApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LandPApi.Models.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ward")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0750d8d3-bfff-45f2-b081-2a86ffe91bfd"),
                            CustomerId = "04be0c35-571e-425c-992e-15a7227286de",
                            Detail = "5",
                            District = "Thành phố Cà Mau",
                            Province = "Cà Mau",
                            Ward = "8"
                        },
                        new
                        {
                            Id = new Guid("3fd64b58-5ded-40ed-876c-027bcc759a75"),
                            CustomerId = "1b0b163d-032f-4e19-9e64-d89bf02f1751",
                            Detail = "Tô Ký",
                            District = "12",
                            Province = "Thành phố Hồ Chí Minh",
                            Ward = "Tân Chánh Hiệp"
                        });
                });

            modelBuilder.Entity("LandPApi.Models.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2ef43281-9c42-466e-ad66-483ff6f46326"),
                            Description = "A branch from korea",
                            LogoUrl = "https://drive.google.com/uc?export=view&id=1JrfIHh1Fi9aM66IMLd2jdZwurx1As6x0",
                            Name = "Samsung"
                        },
                        new
                        {
                            Id = new Guid("36326612-2d44-446f-87cd-d060d14237a6"),
                            Description = "A branch from Ameria",
                            LogoUrl = "https://drive.google.com/uc?export=view&id=1DfzKYG8dsu0C0tNK_5U8GNBM3IE92fsz",
                            Name = "Apple"
                        },
                        new
                        {
                            Id = new Guid("32a244dc-528a-402a-b8e0-d86b31f0b8cb"),
                            Description = "A branch from China",
                            LogoUrl = "https://drive.google.com/uc?export=view&id=1WGo9ev5XnfDETamxPvTVaJJuAYr892Nf",
                            Name = "Xiaomi"
                        },
                        new
                        {
                            Id = new Guid("71d6e1f9-8c22-43e8-ad37-1609dd7bc61e"),
                            Description = "A branch from China",
                            LogoUrl = "https://drive.google.com/uc?export=view&id=1CYKkazDIXzIw_q6ioPB8NlgZTjnhor-N",
                            Name = "Assus"
                        },
                        new
                        {
                            Id = new Guid("04d63fc1-582a-4ad3-9132-b531101220ca"),
                            Description = "A branch from China",
                            LogoUrl = "https://drive.google.com/uc?export=view&id=1Q0u1RB9SfYkxXXmF2s9CPyTXKVY4IN1A",
                            Name = "Dell"
                        },
                        new
                        {
                            Id = new Guid("2d750aa2-ea06-47ea-916c-abb6661f9781"),
                            Description = "A branch from China",
                            LogoUrl = "https://drive.google.com/uc?export=view&id=1T3galDlqvff5zyZd8kf19McJK9V7iAvL",
                            Name = "Suunto"
                        },
                        new
                        {
                            Id = new Guid("fc1a0ff3-92d8-4a16-adb5-8c901bbe48f2"),
                            Description = "A branch from China",
                            LogoUrl = "https://drive.google.com/uc?export=view&id=1F9Sn87qp9kkJbbANHNKSXoE6pYwLPVz-",
                            Name = "Logitech"
                        });
                });

            modelBuilder.Entity("LandPApi.Models.CartItem", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CustomerId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("LandPApi.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bc17dda5-9e53-434d-ab30-32452bfc7d35"),
                            AvatarUrl = "https://drive.google.com/uc?export=view&id=1VPowiqiVfyuL7Pzntp1mqJV748v34zfb",
                            Description = "A smart device",
                            Name = "Smartphone"
                        },
                        new
                        {
                            Id = new Guid("3f8d98cb-a695-4334-bec2-09008670c39a"),
                            AvatarUrl = "https://drive.google.com/uc?export=view&id=15Lo6BabMJo7m9p-VSve4kls1pG2VA1AN",
                            Description = "A smart device",
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = new Guid("a54988d2-7eeb-4e6c-8421-6f3fa5bb91a2"),
                            AvatarUrl = "https://drive.google.com/uc?export=view&id=1EHDwKK-pKe78N_-Ns3RhID7Wg3S2nmDP",
                            Description = "A smart device",
                            Name = "Tablet"
                        },
                        new
                        {
                            Id = new Guid("3649b208-05c6-4129-86bd-df77801d3d39"),
                            AvatarUrl = "https://drive.google.com/uc?export=view&id=1y_ap3ooVR_djmamFvklsm0tx-d9Zrt3V",
                            Description = "A smart device",
                            Name = "Smartwatch"
                        },
                        new
                        {
                            Id = new Guid("76f4c144-6e3f-44bf-a292-8dd21a461b5d"),
                            AvatarUrl = "https://drive.google.com/uc?export=view&id=1N6u8HMtyTtdXWGBxz5AFRzk2KbvB6aVc",
                            Description = "A smart device",
                            Name = "Mouse"
                        });
                });

            modelBuilder.Entity("LandPApi.Models.Customer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "289f6c6a783e4d89b25c847d1ffa4833",
                            AccessFailedCount = 0,
                            BirthDay = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "f063e9f4-3be4-4ba3-a611-b6cf0d587fad",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "landpsupadmika@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Super Admin",
                            NormalizedEmail = "landpsupadmika@gmail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEKUIe6bil4VjV2M15apPqRhWhNQjQvW4yp4lYH3ueZfN7RcvKsECiwkWk6W3EJwu4A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "34a83a86-d6a3-42ad-a929-66f0a1c2b403",
                            TwoFactorEnabled = false,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "landpsupadmika@gmail.com"
                        },
                        new
                        {
                            Id = "43bd8d30-85af-4960-8a9f-d7f7eeeb8571",
                            AccessFailedCount = 0,
                            BirthDay = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "a846ad0f-3bfe-45ee-a093-6841c895ae08",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "landpadmika@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Admin",
                            NormalizedEmail = "landpadmika@gmail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEMIBUk0cZUcqCs2yF1qu580/Xt7GiNDaImlzFZ4gaPqjJOHTeddsuFsvW2IFJ0l02w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "db4fa872-c039-435f-bc1e-4a626413a6f8",
                            TwoFactorEnabled = false,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "landpadmika@gmail.com"
                        },
                        new
                        {
                            Id = "04be0c35-571e-425c-992e-15a7227286de",
                            AccessFailedCount = 0,
                            BirthDay = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "733405a6-2831-409d-af9e-fda4482bf1b4",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "landpuserdemo@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "User",
                            NormalizedEmail = "landpuserdemo@gmail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEFNTWZCk8LwFZwKcu3QNx87BcTUpQuJeyD7wHdLOGw0mvp/MMp1jj9qs0QSR0uuFjQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8bbbede7-b0a5-428a-9e00-511bcab6f8cf",
                            TwoFactorEnabled = false,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "landpuserdemo@gmail.com"
                        },
                        new
                        {
                            Id = "1b0b163d-032f-4e19-9e64-d89bf02f1751",
                            AccessFailedCount = 0,
                            BirthDay = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "1287e7ed-143f-4444-8d4d-73272254e210",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "landpuserdemo1@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "User1",
                            NormalizedEmail = "landpuserdemo1@gmail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEMIKQT22a7WefbHmv7h+BptOkfSBgo6JXlo3MU32zSJvpsBKxHJ4SDm1SEWDukNRyw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a5e79b67-17eb-4990-99d5-d48607f06f2a",
                            TwoFactorEnabled = false,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "landpuserdemo1@gmail.com"
                        });
                });

            modelBuilder.Entity("LandPApi.Models.Document", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Documents");

                    b.HasData(
                        new
                        {
                            Id = "https://drive.google.com/uc?export=view&id=1IzG911rHzKN2p51Ite3JZqDV1FonTt4d",
                            ProductId = new Guid("d01f7780-5cdd-4ff0-b6db-947a1f3d3f04")
                        },
                        new
                        {
                            Id = "https://drive.google.com/uc?export=view&id=1DeA5LM1HQsUEb9tXUHEg27fWqKenJJDG",
                            ProductId = new Guid("257c3301-487b-4c18-bc3d-21ffb71a4d43")
                        },
                        new
                        {
                            Id = "https://drive.google.com/uc?export=view&id=1JgLvP6rxTkkkmdWG7RhyqB4nMnaktLE6",
                            ProductId = new Guid("257c3301-487b-4c18-bc3d-21ffb71a4d43")
                        },
                        new
                        {
                            Id = "https://drive.google.com/uc?export=view&id=1g7NLy-NZE9OTZhH0xctgVXONMNjHpQ4V",
                            ProductId = new Guid("257c3301-487b-4c18-bc3d-21ffb71a4d43")
                        },
                        new
                        {
                            Id = "https://drive.google.com/uc?export=view&id=1JO-t8NpCi9qb9Jx8pmXbdHMvPg8LQAg3",
                            ProductId = new Guid("257c3301-487b-4c18-bc3d-21ffb71a4d43")
                        });
                });

            modelBuilder.Entity("LandPApi.Models.HistoryStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("HistoryStatuses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("854cb2ce-a93a-471c-8a29-f06843766612"),
                            Date = new DateTime(2023, 5, 2, 17, 13, 41, 424, DateTimeKind.Local).AddTicks(8342),
                            OrderId = new Guid("cd9218db-08c0-4af8-9058-0ac6cf7d58b9"),
                            Status = "New"
                        },
                        new
                        {
                            Id = new Guid("f5113cb8-a5b1-41a0-b0c9-c150f325399d"),
                            Date = new DateTime(2023, 5, 2, 17, 13, 41, 424, DateTimeKind.Local).AddTicks(8355),
                            OrderId = new Guid("cd9218db-08c0-4af8-9058-0ac6cf7d58b9"),
                            Status = "Processing"
                        },
                        new
                        {
                            Id = new Guid("92119b84-e7d4-43dc-99a7-e674bd92f907"),
                            Date = new DateTime(2023, 5, 2, 17, 13, 41, 424, DateTimeKind.Local).AddTicks(8356),
                            OrderId = new Guid("cd9218db-08c0-4af8-9058-0ac6cf7d58b9"),
                            Status = "Shipping"
                        },
                        new
                        {
                            Id = new Guid("e255dadb-b8e4-4908-a6be-c81dfc21d2c4"),
                            Date = new DateTime(2023, 5, 2, 17, 13, 41, 424, DateTimeKind.Local).AddTicks(8358),
                            OrderId = new Guid("cd9218db-08c0-4af8-9058-0ac6cf7d58b9"),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = new Guid("849285e7-02a0-4e38-b99b-35ca475b0a13"),
                            Date = new DateTime(2023, 5, 2, 17, 13, 41, 424, DateTimeKind.Local).AddTicks(8360),
                            OrderId = new Guid("6925f34b-4021-4fe9-9155-88b9e0df0678"),
                            Status = "New"
                        },
                        new
                        {
                            Id = new Guid("07614b9b-bf2d-4bad-a16b-a0a41bcf67e3"),
                            Date = new DateTime(2023, 5, 2, 17, 13, 41, 424, DateTimeKind.Local).AddTicks(8361),
                            OrderId = new Guid("6925f34b-4021-4fe9-9155-88b9e0df0678"),
                            Status = "Processing"
                        },
                        new
                        {
                            Id = new Guid("99538a16-efbf-4027-9b91-15cf0d1e767e"),
                            Date = new DateTime(2023, 5, 2, 17, 13, 41, 424, DateTimeKind.Local).AddTicks(8362),
                            OrderId = new Guid("6925f34b-4021-4fe9-9155-88b9e0df0678"),
                            Status = "Shipping"
                        },
                        new
                        {
                            Id = new Guid("a4799b06-f321-42c2-a202-8225890471a0"),
                            Date = new DateTime(2023, 5, 2, 17, 13, 41, 424, DateTimeKind.Local).AddTicks(8376),
                            OrderId = new Guid("6925f34b-4021-4fe9-9155-88b9e0df0678"),
                            Status = "Delivered"
                        },
                        new
                        {
                            Id = new Guid("d2f3e875-6211-4f38-a24e-597f68955b91"),
                            Date = new DateTime(2023, 5, 2, 17, 13, 41, 424, DateTimeKind.Local).AddTicks(8377),
                            OrderId = new Guid("5470e410-d659-4cdc-b84b-bb174a67a2bf"),
                            Status = "New"
                        },
                        new
                        {
                            Id = new Guid("955bb84a-8ad9-448a-b17f-65548aa21145"),
                            Date = new DateTime(2023, 5, 2, 17, 13, 41, 424, DateTimeKind.Local).AddTicks(8379),
                            OrderId = new Guid("5470e410-d659-4cdc-b84b-bb174a67a2bf"),
                            Status = "Processing"
                        },
                        new
                        {
                            Id = new Guid("d3a77831-89d9-4644-a7d0-7a4eca5d3c32"),
                            Date = new DateTime(2023, 5, 2, 17, 13, 41, 424, DateTimeKind.Local).AddTicks(8380),
                            OrderId = new Guid("5470e410-d659-4cdc-b84b-bb174a67a2bf"),
                            Status = "Shipping"
                        },
                        new
                        {
                            Id = new Guid("9f9e0ef6-8abb-436d-9bf4-a555b8e68717"),
                            Date = new DateTime(2023, 5, 2, 17, 13, 41, 424, DateTimeKind.Local).AddTicks(8382),
                            OrderId = new Guid("5470e410-d659-4cdc-b84b-bb174a67a2bf"),
                            Status = "Delivered"
                        });
                });

            modelBuilder.Entity("LandPApi.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cd9218db-08c0-4af8-9058-0ac6cf7d58b9"),
                            AddressId = new Guid("0750d8d3-bfff-45f2-b081-2a86ffe91bfd"),
                            CustomerId = "04be0c35-571e-425c-992e-15a7227286de",
                            Date = new DateTime(2023, 5, 2, 17, 13, 41, 424, DateTimeKind.Local).AddTicks(8232),
                            PaidAt = new DateTime(2023, 5, 2, 17, 13, 41, 424, DateTimeKind.Local).AddTicks(8234),
                            Status = "Delivered",
                            Total = 67640200.0
                        },
                        new
                        {
                            Id = new Guid("6925f34b-4021-4fe9-9155-88b9e0df0678"),
                            AddressId = new Guid("0750d8d3-bfff-45f2-b081-2a86ffe91bfd"),
                            CustomerId = "04be0c35-571e-425c-992e-15a7227286de",
                            Date = new DateTime(2023, 5, 2, 17, 13, 41, 424, DateTimeKind.Local).AddTicks(8237),
                            PaidAt = new DateTime(2023, 5, 2, 17, 13, 41, 424, DateTimeKind.Local).AddTicks(8238),
                            Status = "Delivered",
                            Total = 56154400.0
                        },
                        new
                        {
                            Id = new Guid("5470e410-d659-4cdc-b84b-bb174a67a2bf"),
                            AddressId = new Guid("3fd64b58-5ded-40ed-876c-027bcc759a75"),
                            CustomerId = "1b0b163d-032f-4e19-9e64-d89bf02f1751",
                            Date = new DateTime(2023, 5, 2, 17, 13, 41, 424, DateTimeKind.Local).AddTicks(8240),
                            PaidAt = new DateTime(2023, 5, 2, 17, 13, 41, 424, DateTimeKind.Local).AddTicks(8240),
                            Status = "Delivered",
                            Total = 58364800.0
                        });
                });

            modelBuilder.Entity("LandPApi.Models.OrderDetail", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("PercentSale")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            OrderId = new Guid("cd9218db-08c0-4af8-9058-0ac6cf7d58b9"),
                            ProductId = new Guid("d01f7780-5cdd-4ff0-b6db-947a1f3d3f04"),
                            PercentSale = 0.0,
                            Price = 4990000.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = new Guid("cd9218db-08c0-4af8-9058-0ac6cf7d58b9"),
                            ProductId = new Guid("257c3301-487b-4c18-bc3d-21ffb71a4d43"),
                            PercentSale = 20.0,
                            Price = 15590000.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = new Guid("cd9218db-08c0-4af8-9058-0ac6cf7d58b9"),
                            ProductId = new Guid("13461ff9-0374-4101-a88e-a01dff5f1d8e"),
                            PercentSale = 2.0,
                            Price = 11190000.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = new Guid("cd9218db-08c0-4af8-9058-0ac6cf7d58b9"),
                            ProductId = new Guid("7d7b21dd-b2fe-4179-8238-e871f52fcb2a"),
                            PercentSale = 0.0,
                            Price = 7250000.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = new Guid("6925f34b-4021-4fe9-9155-88b9e0df0678"),
                            ProductId = new Guid("257c3301-487b-4c18-bc3d-21ffb71a4d43"),
                            PercentSale = 20.0,
                            Price = 15590000.0,
                            Quantity = 1
                        },
                        new
                        {
                            OrderId = new Guid("6925f34b-4021-4fe9-9155-88b9e0df0678"),
                            ProductId = new Guid("13461ff9-0374-4101-a88e-a01dff5f1d8e"),
                            PercentSale = 2.0,
                            Price = 11190000.0,
                            Quantity = 2
                        },
                        new
                        {
                            OrderId = new Guid("6925f34b-4021-4fe9-9155-88b9e0df0678"),
                            ProductId = new Guid("7d7b21dd-b2fe-4179-8238-e871f52fcb2a"),
                            PercentSale = 0.0,
                            Price = 7250000.0,
                            Quantity = 3
                        },
                        new
                        {
                            OrderId = new Guid("5470e410-d659-4cdc-b84b-bb174a67a2bf"),
                            ProductId = new Guid("13461ff9-0374-4101-a88e-a01dff5f1d8e"),
                            PercentSale = 2.0,
                            Price = 11190000.0,
                            Quantity = 4
                        },
                        new
                        {
                            OrderId = new Guid("5470e410-d659-4cdc-b84b-bb174a67a2bf"),
                            ProductId = new Guid("7d7b21dd-b2fe-4179-8238-e871f52fcb2a"),
                            PercentSale = 0.0,
                            Price = 7250000.0,
                            Quantity = 2
                        });
                });

            modelBuilder.Entity("LandPApi.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FolderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PercentSale")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d01f7780-5cdd-4ff0-b6db-947a1f3d3f04"),
                            BrandId = new Guid("2ef43281-9c42-466e-ad66-483ff6f46326"),
                            CategoryId = new Guid("bc17dda5-9e53-434d-ab30-32452bfc7d35"),
                            Description = "Màn hình:\r\n\r\nPLS TFT LCD6.6\"Full HD+\r\nHệ điều hành:\r\n\r\nAndroid 12\r\nCamera sau:\r\n\r\nChính 50 MP & Phụ 5 MP, 2 MP, 2 MP\r\nCamera trước:\r\n\r\n8 MP\r\nChip:\r\n\r\nSnapdragon 680\r\nRAM:\r\n\r\n4 GB\r\nDung lượng lưu trữ:\r\n\r\n128 GB\r\nSIM:\r\n\r\n2 Nano SIMHỗ trợ 4G\r\nPin, Sạc:\r\n\r\n5000 mAh25 W",
                            FolderId = "12oUrvgsYTJhM4WkmXuWd1f8NmbvOe9Gn",
                            ImageUrl = "https://drive.google.com/uc?export=view&id=1k0K8y37j9HLnI8C7qYy92mjOzgnY4kSL",
                            Name = "Samsung Galaxy A23",
                            PercentSale = 0.0,
                            Price = 4990000.0,
                            Quantity = 100,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = new Guid("257c3301-487b-4c18-bc3d-21ffb71a4d43"),
                            BrandId = new Guid("2ef43281-9c42-466e-ad66-483ff6f46326"),
                            CategoryId = new Guid("bc17dda5-9e53-434d-ab30-32452bfc7d35"),
                            Description = "Màn hình:\r\n\r\nOLED6.1\"Super Retina XDR\r\nHệ điều hành:\r\n\r\niOS 15\r\nCamera sau:\r\n\r\n2 camera 12 MP\r\nCamera trước:\r\n\r\n12 MP\r\nChip:\r\n\r\nApple A14 Bionic\r\nRAM:\r\n\r\n4 GB\r\nDung lượng lưu trữ:\r\n\r\n64 GB\r\nSIM:\r\n\r\n1 Nano SIM & 1 eSIMHỗ trợ 5G\r\nPin, Sạc:\r\n\r\n2815 mAh20 W",
                            FolderId = "1b9JWfgUruHr6j3U3XalWbAD2UO329_6X",
                            ImageUrl = "https://drive.google.com/uc?export=view&id=1yAleLMwDTEfXJNZF_eM8s4vkU8TFm9By",
                            Name = "Iphone 12",
                            PercentSale = 20.0,
                            Price = 15590000.0,
                            Quantity = 50,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = new Guid("13c2386e-1348-42ef-8de1-46d7515eb3df"),
                            BrandId = new Guid("32a244dc-528a-402a-b8e0-d86b31f0b8cb"),
                            CategoryId = new Guid("bc17dda5-9e53-434d-ab30-32452bfc7d35"),
                            Description = "Xiaomi Redmi Note 12 Pro 5G là mẫu điện thoại thuộc dòng Redmi Note được chính thức ra mắt trong năm 2023, máy mang trên mình những cải tiến vượt trội về thiết kế, camera và hiệu năng, đáp ứng mượt mà hầu hết các nhu cầu khác nhau của người dùng.",
                            FolderId = "1gBdpMXybH0HOxSKI6g9AdmisL9IUMfPq",
                            ImageUrl = "https://drive.google.com/uc?export=view&id=190zjmRvUnsTZdB4iDizNBjqKI_fk5L3a",
                            Name = "Xiaomi Redmi Note 12 Pro 5G",
                            PercentSale = 2.0,
                            Price = 9960000.0,
                            Quantity = 50,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = new Guid("c2c75508-8eac-47de-a3fa-43c44ce8e917"),
                            BrandId = new Guid("32a244dc-528a-402a-b8e0-d86b31f0b8cb"),
                            CategoryId = new Guid("bc17dda5-9e53-434d-ab30-32452bfc7d35"),
                            Description = "Xiaomi 12T series đã ra mắt trong sự kiện của Xiaomi vào ngày 4/10, trong đó có Xiaomi 12T 5G 128GB - máy sở hữu nhiều công nghệ hàng đầu trong giới smartphone tiêu biểu như: Chipset mạnh mẽ đến từ MediaTek, camera 108 MP sắc nét cùng khả năng sạc 120 W siêu nhanh.",
                            FolderId = "1RvQvCVJ2wk72oMqDuYfeuTBHSIHNhplS",
                            ImageUrl = "https://drive.google.com/uc?export=view&id=165CbvBDjo8PPjxn2MPHVe2YrZPZ1oCwd",
                            Name = "Xiaomi 12T 5G 128GB",
                            PercentSale = 0.0,
                            Price = 9890000.0,
                            Quantity = 3,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = new Guid("5d7beeaf-f51e-44bb-ae26-aadb1bdc0276"),
                            BrandId = new Guid("71d6e1f9-8c22-43e8-ad37-1609dd7bc61e"),
                            CategoryId = new Guid("3f8d98cb-a695-4334-bec2-09008670c39a"),
                            Description = "Nếu bạn đang tìm kiếm một chiếc laptop gaming nhưng vẫn sở hữu một mức giá phải chăng thì laptop Asus TUF Gaming F15 FX506LHB i5 (HN188W) sẽ là sự lựa chọn đáng cân nhắc với card đồ họa rời NVIDIA GeForce GTX mạnh mẽ cùng phong cách thiết kế cứng cáp, độc đáo. ",
                            FolderId = "1504cqv26tU1E4JAWix9Ajxwh3XCH8tOv",
                            ImageUrl = "https://drive.google.com/uc?export=view&id=1s_UzQewLQ4zb7cX25cwUYAlVa3CpuCP9",
                            Name = "TUF Gaming F15",
                            PercentSale = 0.0,
                            Price = 16990000.0,
                            Quantity = 50,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = new Guid("d5682976-7d8c-4549-884c-e85f73ddbed3"),
                            BrandId = new Guid("04d63fc1-582a-4ad3-9132-b531101220ca"),
                            CategoryId = new Guid("3f8d98cb-a695-4334-bec2-09008670c39a"),
                            Description = "Laptop Dell Vostro 3510 i5 (P112F002BBL) sở hữu cấu hình mạnh mẽ, đa nhiệm mượt mà trên sức mạnh của bộ vi xử lý Intel thế hệ 11, cùng một thiết kế đơn giản mà sang đẹp, sẽ là lựa chọn đắt giá đáp ứng nhu cầu học tập, làm việc hay giải trí của bạn.",
                            FolderId = "1R9qzBw6zNwBARHF8aGu2_qJYlil161yl",
                            ImageUrl = "https://drive.google.com/uc?export=view&id=1ELd9fd2dk2meSyxz-hVnsIp8_gFrnHxp",
                            Name = "Dell Vostro 3510",
                            PercentSale = 20.0,
                            Price = 17990000.0,
                            Quantity = 10,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = new Guid("3e9d9046-0534-44cf-a0fa-746a31acad9f"),
                            BrandId = new Guid("36326612-2d44-446f-87cd-d060d14237a6"),
                            CategoryId = new Guid("a54988d2-7eeb-4e6c-8421-6f3fa5bb91a2"),
                            Description = "Sau thành công của iPad 8, Apple cho đã cho ra mắt máy tính bảng iPad 9 WiFi 64GB - phiên bản tiếp theo của dòng iPad 10.2 inch, về cơ bản nó kế thừa những điểm mạnh từ các phiên bản trước đó và được cải tiến thêm hiệu suất, trải nghiệm người dùng nhằm giúp nhu cầu sử dụng giải trí và làm việc tiện lợi, linh hoạt hơn",
                            FolderId = "1SZ3o96HmpNycsXIeOzuXBDF3dgh6v85o",
                            ImageUrl = "https://drive.google.com/uc?export=view&id=1IK5bpXd3iGWJbMDOS5c_zG5Zk5th3hhl",
                            Name = "iPad 9",
                            PercentSale = 0.0,
                            Price = 7990000.0,
                            Quantity = 10,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = new Guid("13461ff9-0374-4101-a88e-a01dff5f1d8e"),
                            BrandId = new Guid("36326612-2d44-446f-87cd-d060d14237a6"),
                            CategoryId = new Guid("a54988d2-7eeb-4e6c-8421-6f3fa5bb91a2"),
                            Description = "Sau khi trình làng hàng loạt mẫu iPhone vào tháng 09/2022 thì Apple cũng đã tiếp tục giới thiệu series iPad mới cho năm 2022. Trong đó iPad 10 WiFi 64GB là cái tên được hãng chú trọng khá nhiều về việc tối ưu giá thành nhằm giúp người dùng có thể dễ dàng tiếp cận. Máy hỗ trợ hệ điều hành iPadOS 16 cùng con chip Apple A14 Bionic giúp mang lại hiệu năng vượt trội.",
                            FolderId = "18kx0xh8gVJAJllf-4ZVeFZFfkJHI1zkX",
                            ImageUrl = "https://drive.google.com/uc?export=view&id=1PjgSj70e2Oc1GC-DJBiVkzs77mAdEokF",
                            Name = "iPad 10",
                            PercentSale = 2.0,
                            Price = 11190000.0,
                            Quantity = 10,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = new Guid("7d7b21dd-b2fe-4179-8238-e871f52fcb2a"),
                            BrandId = new Guid("2d750aa2-ea06-47ea-916c-abb6661f9781"),
                            CategoryId = new Guid("3649b208-05c6-4129-86bd-df77801d3d39"),
                            Description = "Đồng hồ thông minh Suunto 7 Dây silicone phiên bản màu đen trang bị mặt kính cường lực chống va đập, màn hình AMOLED 1.97 inch (454 x 454 pixels) cùng độ sáng lên tới 1000 nits, vì thế có thể hiển thị sắc nét ngay cả khi ở điều kiện có ánh sáng mặt trời. Đặc biệt, với thiết kế dây đeo silicone tạo cảm giác mềm mại và dễ chịu khi đeo trong thời gian dài.",
                            FolderId = "15B4NY2lAFY9DXr1Z40hwoQNjI5ZjnpZ4",
                            ImageUrl = "https://drive.google.com/uc?export=view&id=1-nQviihO_G_HGipaWd72aRUURK4zkm6S",
                            Name = "Suunto 7",
                            PercentSale = 0.0,
                            Price = 7250000.0,
                            Quantity = 5,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = new Guid("777ffbe5-1f43-4b6c-80d3-6b3cffbcb721"),
                            BrandId = new Guid("2ef43281-9c42-466e-ad66-483ff6f46326"),
                            CategoryId = new Guid("3649b208-05c6-4129-86bd-df77801d3d39"),
                            Description = "Sau thành công của dòng Galaxy Watch4, tháng 8/2022 ông lớn công nghệ Samsung đã cho ra mắt thế hệ smartwatch tiếp theo của hãng mang tên Samsung Galaxy Watch5 40 mm.",
                            FolderId = "1v5XPVE3A_7XnX4yUf8OekLE54mHXr_CZ",
                            ImageUrl = "https://drive.google.com/uc?export=view&id=17uBw10YiFMD2ET9pw_wiXkznPsQrAhr0",
                            Name = "Samsung Galaxy Watch5",
                            PercentSale = 0.0,
                            Price = 5490000.0,
                            Quantity = 10,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = new Guid("61a1dce1-164c-4a2f-a6e1-6397c5033bfb"),
                            BrandId = new Guid("fc1a0ff3-92d8-4a16-adb5-8c901bbe48f2"),
                            CategoryId = new Guid("76f4c144-6e3f-44bf-a292-8dd21a461b5d"),
                            Description = "Chuột Không dây Bluetooth Silent Logitech Signature M650 sở hữu kiểu dáng công thái học cùng độ phân giải lớn, đáp ứng tốt gần như mọi nhu cầu từ sử dụng cơ bản tới những tác vụ chuyên nghiệp của người dùng.",
                            FolderId = "1M0-dUHbo7g_pkLPbQu9NMTPc9tnGkwr7",
                            ImageUrl = "https://drive.google.com/uc?export=view&id=1ukyWOlXUIJzxVzjmNN5hPlrnHN0yET7b",
                            Name = "Bluetooth Silent Logitech Signature M650",
                            PercentSale = 0.0,
                            Price = 765000.0,
                            Quantity = 10,
                            Unit = "Unit"
                        });
                });

            modelBuilder.Entity("LandPApi.Models.Review", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("CustomerId", "ProductId", "OrderId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            CustomerId = "04be0c35-571e-425c-992e-15a7227286de",
                            ProductId = new Guid("d01f7780-5cdd-4ff0-b6db-947a1f3d3f04"),
                            OrderId = new Guid("cd9218db-08c0-4af8-9058-0ac6cf7d58b9"),
                            Comment = "Good",
                            Date = new DateTime(2023, 5, 2, 17, 13, 41, 424, DateTimeKind.Local).AddTicks(8406),
                            Rating = 5
                        },
                        new
                        {
                            CustomerId = "04be0c35-571e-425c-992e-15a7227286de",
                            ProductId = new Guid("13461ff9-0374-4101-a88e-a01dff5f1d8e"),
                            OrderId = new Guid("cd9218db-08c0-4af8-9058-0ac6cf7d58b9"),
                            Comment = "More than expected!",
                            Date = new DateTime(2023, 5, 2, 17, 13, 41, 424, DateTimeKind.Local).AddTicks(8408),
                            Rating = 5
                        },
                        new
                        {
                            CustomerId = "04be0c35-571e-425c-992e-15a7227286de",
                            ProductId = new Guid("7d7b21dd-b2fe-4179-8238-e871f52fcb2a"),
                            OrderId = new Guid("cd9218db-08c0-4af8-9058-0ac6cf7d58b9"),
                            Comment = "Wonderful",
                            Date = new DateTime(2023, 5, 2, 17, 13, 41, 424, DateTimeKind.Local).AddTicks(8409),
                            Rating = 5
                        },
                        new
                        {
                            CustomerId = "04be0c35-571e-425c-992e-15a7227286de",
                            ProductId = new Guid("257c3301-487b-4c18-bc3d-21ffb71a4d43"),
                            OrderId = new Guid("cd9218db-08c0-4af8-9058-0ac6cf7d58b9"),
                            Comment = "Ok",
                            Date = new DateTime(2023, 5, 2, 17, 13, 41, 424, DateTimeKind.Local).AddTicks(8410),
                            Rating = 4
                        },
                        new
                        {
                            CustomerId = "04be0c35-571e-425c-992e-15a7227286de",
                            ProductId = new Guid("13461ff9-0374-4101-a88e-a01dff5f1d8e"),
                            OrderId = new Guid("6925f34b-4021-4fe9-9155-88b9e0df0678"),
                            Comment = "More than expected!",
                            Date = new DateTime(2023, 5, 2, 17, 13, 41, 424, DateTimeKind.Local).AddTicks(8411),
                            Rating = 5
                        },
                        new
                        {
                            CustomerId = "04be0c35-571e-425c-992e-15a7227286de",
                            ProductId = new Guid("7d7b21dd-b2fe-4179-8238-e871f52fcb2a"),
                            OrderId = new Guid("6925f34b-4021-4fe9-9155-88b9e0df0678"),
                            Comment = "Wonderful",
                            Date = new DateTime(2023, 5, 2, 17, 13, 41, 424, DateTimeKind.Local).AddTicks(8412),
                            Rating = 5
                        },
                        new
                        {
                            CustomerId = "04be0c35-571e-425c-992e-15a7227286de",
                            ProductId = new Guid("257c3301-487b-4c18-bc3d-21ffb71a4d43"),
                            OrderId = new Guid("6925f34b-4021-4fe9-9155-88b9e0df0678"),
                            Comment = "Ok",
                            Date = new DateTime(2023, 5, 2, 17, 13, 41, 424, DateTimeKind.Local).AddTicks(8413),
                            Rating = 4
                        },
                        new
                        {
                            CustomerId = "1b0b163d-032f-4e19-9e64-d89bf02f1751",
                            ProductId = new Guid("7d7b21dd-b2fe-4179-8238-e871f52fcb2a"),
                            OrderId = new Guid("5470e410-d659-4cdc-b84b-bb174a67a2bf"),
                            Comment = "Wonderful",
                            Date = new DateTime(2023, 5, 2, 17, 13, 41, 424, DateTimeKind.Local).AddTicks(8414),
                            Rating = 5
                        });
                });

            modelBuilder.Entity("LandPApi.Models.View", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("CustomerId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("Views");

                    b.HasData(
                        new
                        {
                            CustomerId = "04be0c35-571e-425c-992e-15a7227286de",
                            ProductId = new Guid("c2c75508-8eac-47de-a3fa-43c44ce8e917"),
                            Date = new DateTime(2023, 5, 2, 17, 13, 41, 424, DateTimeKind.Local).AddTicks(8179)
                        },
                        new
                        {
                            CustomerId = "04be0c35-571e-425c-992e-15a7227286de",
                            ProductId = new Guid("13c2386e-1348-42ef-8de1-46d7515eb3df"),
                            Date = new DateTime(2023, 5, 2, 17, 13, 41, 424, DateTimeKind.Local).AddTicks(8195)
                        },
                        new
                        {
                            CustomerId = "1b0b163d-032f-4e19-9e64-d89bf02f1751",
                            ProductId = new Guid("c2c75508-8eac-47de-a3fa-43c44ce8e917"),
                            Date = new DateTime(2023, 5, 2, 17, 13, 41, 424, DateTimeKind.Local).AddTicks(8196)
                        },
                        new
                        {
                            CustomerId = "1b0b163d-032f-4e19-9e64-d89bf02f1751",
                            ProductId = new Guid("13c2386e-1348-42ef-8de1-46d7515eb3df"),
                            Date = new DateTime(2023, 5, 2, 17, 13, 41, 424, DateTimeKind.Local).AddTicks(8197)
                        },
                        new
                        {
                            CustomerId = "1b0b163d-032f-4e19-9e64-d89bf02f1751",
                            ProductId = new Guid("7d7b21dd-b2fe-4179-8238-e871f52fcb2a"),
                            Date = new DateTime(2023, 5, 2, 17, 13, 41, 424, DateTimeKind.Local).AddTicks(8201)
                        },
                        new
                        {
                            CustomerId = "1b0b163d-032f-4e19-9e64-d89bf02f1751",
                            ProductId = new Guid("d01f7780-5cdd-4ff0-b6db-947a1f3d3f04"),
                            Date = new DateTime(2023, 5, 2, 17, 13, 41, 424, DateTimeKind.Local).AddTicks(8202)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "289f6c6a783e4d89b25c847d1ffa4833",
                            ConcurrencyStamp = "0",
                            Name = "SuperAdmin",
                            NormalizedName = "SuperAdmin"
                        },
                        new
                        {
                            Id = "43bd8d30-85af-4960-8a9f-d7f7eeeb8571",
                            ConcurrencyStamp = "1",
                            Name = "Admin",
                            NormalizedName = "Admin"
                        },
                        new
                        {
                            Id = "04be0c35-571e-425c-992e-15a7227286de",
                            ConcurrencyStamp = "2",
                            Name = "User",
                            NormalizedName = "User"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "289f6c6a783e4d89b25c847d1ffa4833",
                            RoleId = "289f6c6a783e4d89b25c847d1ffa4833"
                        },
                        new
                        {
                            UserId = "43bd8d30-85af-4960-8a9f-d7f7eeeb8571",
                            RoleId = "43bd8d30-85af-4960-8a9f-d7f7eeeb8571"
                        },
                        new
                        {
                            UserId = "04be0c35-571e-425c-992e-15a7227286de",
                            RoleId = "04be0c35-571e-425c-992e-15a7227286de"
                        },
                        new
                        {
                            UserId = "1b0b163d-032f-4e19-9e64-d89bf02f1751",
                            RoleId = "04be0c35-571e-425c-992e-15a7227286de"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LandPApi.Models.Address", b =>
                {
                    b.HasOne("LandPApi.Models.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("LandPApi.Models.CartItem", b =>
                {
                    b.HasOne("LandPApi.Models.Customer", "Customer")
                        .WithMany("CartItems")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LandPApi.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("LandPApi.Models.Document", b =>
                {
                    b.HasOne("LandPApi.Models.Product", "Product")
                        .WithMany("Documents")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("LandPApi.Models.HistoryStatus", b =>
                {
                    b.HasOne("LandPApi.Models.Order", "Order")
                        .WithMany("HistoryStatuses")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("LandPApi.Models.Order", b =>
                {
                    b.HasOne("LandPApi.Models.Address", "Address")
                        .WithMany("Orders")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LandPApi.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId");

                    b.Navigation("Address");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("LandPApi.Models.OrderDetail", b =>
                {
                    b.HasOne("LandPApi.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LandPApi.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("LandPApi.Models.Product", b =>
                {
                    b.HasOne("LandPApi.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LandPApi.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LandPApi.Models.Review", b =>
                {
                    b.HasOne("LandPApi.Models.Customer", "Customer")
                        .WithMany("Reviews")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LandPApi.Models.Order", "Order")
                        .WithMany("Reviews")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LandPApi.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("LandPApi.Models.View", b =>
                {
                    b.HasOne("LandPApi.Models.Customer", "Customer")
                        .WithMany("Views")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LandPApi.Models.Product", "Product")
                        .WithMany("Views")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LandPApi.Models.Customer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LandPApi.Models.Customer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LandPApi.Models.Customer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LandPApi.Models.Customer", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LandPApi.Models.Address", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("LandPApi.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("LandPApi.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("LandPApi.Models.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("CartItems");

                    b.Navigation("Orders");

                    b.Navigation("Reviews");

                    b.Navigation("Views");
                });

            modelBuilder.Entity("LandPApi.Models.Order", b =>
                {
                    b.Navigation("HistoryStatuses");

                    b.Navigation("OrderDetails");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("LandPApi.Models.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Documents");

                    b.Navigation("OrderDetails");

                    b.Navigation("Reviews");

                    b.Navigation("Views");
                });
#pragma warning restore 612, 618
        }
    }
}
